version: '3.9'
services:
   web:
     build:
       context: .
       dockerfile: Dockerfile
     image: cope:production
     command: bash -c "python3 manage.py migrate && python3 manage.py collectstatic --noinput && python3 manage.py runserver 0.0.0.0:8000"
     volumes:
      - .:/app
     ports:
         - 80:8000
     env_file:
       - ./acebc/.env