# Generated by Django 4.1.2 on 2023-05-21 20:54

import acebc.storage.storage_backends
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("body", models.TextField(max_length=1000000)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=True)),
                ("edited", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("date_added",),
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Title")),
                (
                    "body",
                    tinymce.models.HTMLField(
                        blank=True, default="", max_length=1000000
                    ),
                ),
                ("date_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "youtube",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Youtube Share Link",
                    ),
                ),
                ("tag", models.CharField(max_length=255, verbose_name="Tag")),
                ("username", models.CharField(max_length=255, verbose_name="Username")),
                (
                    "usergroup",
                    models.CharField(
                        default="admin", max_length=255, verbose_name="Usergroup"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        default="Other", max_length=255, verbose_name="Label"
                    ),
                ),
                ("comments_count", models.IntegerField(default=0)),
                ("edited", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UploadPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=acebc.storage.storage_backends.PrivateMediaStorage(),
                        upload_to="documents/",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="forum.post"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=acebc.storage.storage_backends.PrivateMediaStorage(),
                        upload_to="images/",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="forum.post"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommentReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("body", models.TextField(max_length=1000000)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=True)),
                ("edited", models.BooleanField(default=False)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="forum.comment",
                    ),
                ),
            ],
            options={
                "ordering": ("date_added",),
            },
        ),
        migrations.AddField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="forum.post",
            ),
        ),
    ]
