# Generated by Django 4.1.2 on 2023-03-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0004_alter_aboutme_about_me"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
