# Use Original Base Image
FROM kolss/cope:base

# copy requiremnets.txt to the Docker workdir and install all dependencies
COPY requirements.txt /app/requirements.txt
RUN python3 -m pip install -r requirements.txt